/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Status
         * @description Return recent worker evidence only; this endpoint never probes an LLM.
         */
        get: operations["get_llm_status_api_v1_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm-status/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Llm Status
         * @description Run one user-requested live reachability probe without changing worker status.
         */
        post: operations["probe_llm_status_api_v1_llm_status_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Binaries */
        get: operations["list_binaries_api_v1_binaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Binary
         * @description Stream a raw Ghidra JSON export to staging and enqueue its import.
         *
         *     The configured byte cap is enforced during the read: Content-Length is
         *     merely an early rejection optimization because chunked requests lack it.
         */
        post: operations["import_binary_api_v1_binaries_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/decompile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decompile Binary
         * @description Stream a raw binary and analyze it with the configured local decompiler.
         */
        post: operations["decompile_binary_api_v1_binaries_decompile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Status */
        get: operations["get_import_status_api_v1_binaries_imports__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Import */
        delete: operations["cancel_import_api_v1_binaries_imports__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Binary */
        delete: operations["delete_binary_api_v1_binaries__binary_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/entry-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry Points */
        get: operations["get_entry_points_api_v1_binaries__binary_id__entry_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Binary Functions */
        get: operations["search_binary_functions_api_v1_binaries__binary_id__functions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/functions/by-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Function By Address */
        get: operations["resolve_function_by_address_api_v1_binaries__binary_id__functions_by_address_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/functions/{function_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Function */
        get: operations["get_function_api_v1_functions__function_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Function */
        patch: operations["update_function_api_v1_functions__function_id__patch"];
        trace?: never;
    };
    "/api/v1/functions/{function_id}/neighbours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Neighbours */
        get: operations["get_neighbours_api_v1_functions__function_id__neighbours_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Binary Views */
        get: operations["list_binary_views_api_v1_binaries__binary_id__views_get"];
        put?: never;
        /** Create Binary View */
        post: operations["create_binary_view_api_v1_binaries__binary_id__views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/last-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Last View */
        post: operations["set_last_view_api_v1_binaries__binary_id__last_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View */
        get: operations["get_view_api_v1_views__view_id__get"];
        put?: never;
        post?: never;
        /** Delete View */
        delete: operations["delete_view_api_v1_views__view_id__delete"];
        options?: never;
        head?: never;
        /** Patch View */
        patch: operations["patch_view_api_v1_views__view_id__patch"];
        trace?: never;
    };
    "/api/v1/views/{view_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate View */
        post: operations["duplicate_view_api_v1_views__view_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/views/{view_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch View Nodes */
        patch: operations["patch_view_nodes_api_v1_views__view_id__nodes_patch"];
        trace?: never;
    };
    "/api/v1/views/{view_id}/open-functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Functions */
        post: operations["open_functions_api_v1_views__view_id__open_functions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/functions/{function_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demand Summary
         * @description Demand a summary (endpoint 17). Returns **202** immediately if new
         *     work was scheduled (C5a — never blocks on the LLM), or **200** if a
         *     ready result was already cached (C3).
         */
        post: operations["demand_summary_api_v1_functions__function_id__summary_post"];
        /**
         * Release Summary
         * @description Release demand / cancel if unstarted (endpoint 18, C8). Advisory only
         *     — an in-flight generation is never interrupted.
         */
        delete: operations["release_summary_api_v1_functions__function_id__summary_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binaries/{binary_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Binary Summaries
         * @description TESTING affordance: wipe every LLM summary (`summary_short`/
         *     `summary_long` and friends) for all functions of the binary.
         */
        delete: operations["clear_binary_summaries_api_v1_binaries__binary_id__summaries_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/functions/{function_id}/summary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Summary
         * @description Force regeneration, bypassing the cache (endpoint 19, C7).
         */
        post: operations["regenerate_summary_api_v1_functions__function_id__summary_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Queue snapshot for the chip (endpoint 20).
         */
        get: operations["get_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/cancel-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Pending
         * @description Drop all queued-unstarted items (endpoint 21).
         */
        post: operations["cancel_pending_api_v1_queue_cancel_pending_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterIdentityDto */
        AdapterIdentityDto: {
            /** Ghidra */
            ghidra: string;
            /** Llm */
            llm: string;
            /** Llmmodel */
            llmModel: string;
        };
        /** AppConfigDto */
        AppConfigDto: {
            /** Tablerowcap */
            tableRowCap: number;
            /** Callersuppressthreshold */
            callerSuppressThreshold: number;
            /** Utilityfaninthreshold */
            utilityFanInThreshold: number;
            /** Fanoutallhardcap */
            fanOutAllHardCap: number;
            /** Nodecountsoftwarning */
            nodeCountSoftWarning: number;
            /** Cardwidthpx */
            cardWidthPx: number;
            /** Summaryconcurrency */
            summaryConcurrency: number;
            /** Layoutheightchangethresholdpx */
            layoutHeightChangeThresholdPx: number;
            /** Layoutanimationms */
            layoutAnimationMs: number;
            /** Summarydemanddebouncems */
            summaryDemandDebounceMs: number;
            /** Publicmode */
            publicMode: boolean;
            /** Nodecolorpalette */
            nodeColorPalette: string[];
            adapters: components["schemas"]["AdapterIdentityDto"];
        };
        /** BinarySummaryDto */
        BinarySummaryDto: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Analysisimagebase */
            analysisImageBase: number | null;
            /** Functioncount */
            functionCount: number;
            /** Edgecount */
            edgeCount: number;
            /** Lastviewid */
            lastViewId: number | null;
            /** Createdat */
            createdAt: string;
        };
        /** CameraDto */
        CameraDto: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zoom */
            zoom: number;
        };
        /**
         * CancelPendingResponseDto
         * @description ``POST /queue/cancel-pending`` (endpoint 21) response.
         */
        CancelPendingResponseDto: {
            /** Cancelledcount */
            cancelledCount: number;
        };
        /**
         * DecompilerHealthDto
         * @description Reachability of the configured local raw-binary decompiler.
         */
        DecompilerHealthDto: {
            /** Reachable */
            reachable: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** EntryPointDto */
        EntryPointDto: {
            /** Id */
            id: number;
            /** Address */
            address: number;
            /** Displayname */
            displayName: string;
            /** Fanout */
            fanOut: number;
            /** Fanin */
            fanIn: number;
        };
        /** EntryPointsDto */
        EntryPointsDto: {
            /** Entrypoints */
            entryPoints: components["schemas"]["EntryPointDto"][];
        };
        /** FunctionDto */
        FunctionDto: {
            /** Id */
            id: number;
            /** Binaryid */
            binaryId: number;
            /** Address */
            address: number;
            /** Displayname */
            displayName: string;
            /** Name */
            name: string;
            /** Nameanalyst */
            nameAnalyst: string | null;
            /** Namellm */
            nameLlm: string | null;
            /** Isrenamed */
            isRenamed: boolean;
            /** Parameters */
            parameters: components["schemas"]["FunctionParamDto"][];
            /** Signature */
            signature: string | null;
            /** Assembly */
            assembly: string | null;
            /** Codec */
            codeC: string | null;
            /** Kind */
            kind: string;
            /** Placeholdermodule */
            placeholderModule: string | null;
            /** Fanin */
            fanIn: number;
            /** Fanout */
            fanOut: number;
            /** Isutility */
            isUtility: boolean;
            /** Utilitysource */
            utilitySource: string;
            /** Utilityoverride */
            utilityOverride: string | null;
            /** Isentrypoint */
            isEntryPoint: boolean;
            summary: components["schemas"]["FunctionSummaryStateDto"];
            /** Notes */
            notes: string;
            /** Hasnotes */
            hasNotes: boolean;
            /** Notesupdatedat */
            notesUpdatedAt: string | null;
            /** Calleecount */
            calleeCount: number;
            /** Callercount */
            callerCount: number;
            /** Hasindirectcalls */
            hasIndirectCalls: boolean;
        };
        /** FunctionParamDto */
        FunctionParamDto: {
            /** Ordinal */
            ordinal: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** FunctionSearchPageDto */
        FunctionSearchPageDto: {
            /** Rows */
            rows: components["schemas"]["FunctionSearchRowDto"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query: string | null;
        };
        /**
         * FunctionSearchRowDto
         * @description A narrow row for the search results list — no code, no long summary,
         *     matching the `NeighbourRowDto` philosophy of TAD §3.4.
         */
        FunctionSearchRowDto: {
            /** Id */
            id: number;
            /** Address */
            address: number;
            /** Displayname */
            displayName: string;
            /** Isrenamed */
            isRenamed: boolean;
            /** Kind */
            kind: string;
            /** Isutility */
            isUtility: boolean;
            /** Fanin */
            fanIn: number;
            /** Hasnotes */
            hasNotes: boolean;
            /** Isentrypoint */
            isEntryPoint: boolean;
        };
        /** FunctionSummaryStateDto */
        FunctionSummaryStateDto: {
            /** Status */
            status: string;
            /** Short */
            short: string | null;
            /** Long */
            long: string | null;
            /** Model */
            model: string | null;
            /** Adapter */
            adapter: string | null;
            /** Errorcode */
            errorCode: string | null;
            /** Lowconfidence */
            lowConfidence: boolean;
            /** Generatedat */
            generatedAt: string | null;
            /** Isstale */
            isStale: boolean;
        };
        /**
         * FunctionUpdateDto
         * @description ``PATCH /functions/{id}`` request body (D36/E2c).
         *
         *     Every field is optional-and-absent-means-"leave unchanged" (Pydantic v2
         *     ``model_fields_set`` is used by the service layer to distinguish "not
         *     provided" from "explicitly set to null"). M0 scope is `utility_override`
         *     only — `name_analyst`/`notes` are I10.
         */
        FunctionUpdateDto: {
            /** Utilityoverride */
            utilityOverride?: ("always" | "never") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDto */
        HealthDto: {
            /** Status */
            status: string;
            /** Dbok */
            dbOk: boolean;
            /** Migrationrevision */
            migrationRevision: string | null;
            /** Ghidraadapter */
            ghidraAdapter: string;
            /** Llmadapter */
            llmAdapter: string;
            llmHealth: components["schemas"]["LlmHealthDto"];
            decompilerHealth: components["schemas"]["DecompilerHealthDto"];
        };
        /**
         * ImportJobAcceptedDto
         * @description Returned as soon as a raw export has been staged safely.
         */
        ImportJobAcceptedDto: {
            /** Jobid */
            jobId: string;
            phase: components["schemas"]["ImportJobPhase"];
            /** Bytesreceived */
            bytesReceived: number;
            /** Sourcekind */
            sourceKind: string;
        };
        /**
         * ImportJobPhase
         * @description Observable phases for a staged Ghidra import.
         * @enum {string}
         */
        ImportJobPhase: "uploading" | "queued" | "decompiling" | "importing" | "completed" | "failed" | "cancelled";
        /**
         * ImportJobStatusDto
         * @description Process-local import-job state.
         *
         *     Jobs intentionally do not survive an API process restart in this first
         *     scalable-import iteration. `failure_samples` is bounded by configuration.
         */
        ImportJobStatusDto: {
            /** Jobid */
            jobId: string;
            phase: components["schemas"]["ImportJobPhase"];
            /** Bytesreceived */
            bytesReceived: number;
            /** Sourcekind */
            sourceKind: string;
            result?: components["schemas"]["ImportResultDto"] | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Errordetails */
            errorDetails?: {
                [key: string]: unknown;
            } | null;
            /** Failuresamples */
            failureSamples?: string[];
        };
        /**
         * ImportResultDto
         * @description Outcome of an import, returned synchronously (I12).
         *
         *     No SSE ``binary`` event is emitted (that transport is unbuilt in M0); the
         *     client refetches ``GET /binaries`` on success instead.
         */
        ImportResultDto: {
            /** Binaryid */
            binaryId: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Functionsinserted */
            functionsInserted: number;
            /** Functionsupdated */
            functionsUpdated: number;
            /** Edgesinserted */
            edgesInserted: number;
            /** Placeholderscreated */
            placeholdersCreated: number;
            /** Failures */
            failures?: string[];
        };
        /** InFlightItemDto */
        InFlightItemDto: {
            /** Functionid */
            functionId: number;
            /** Displayname */
            displayName: string;
            /** Startedat */
            startedAt?: string | null;
        };
        /**
         * LlmHealthDto
         * @description AM5: adapter reachability, so the UI can tell "no summaries because
         *     misconfigured" from "no summaries yet".
         */
        LlmHealthDto: {
            /** Reachable */
            reachable: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * LlmProbeDto
         * @description Result of an explicitly requested, live adapter reachability probe.
         */
        LlmProbeDto: {
            /** Reachable */
            reachable: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * LlmStatusDto
         * @description Last meaningful worker outcome for the currently configured LLM.
         */
        LlmStatusDto: {
            /** Adapter */
            adapter: string;
            /** Model */
            model: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "success" | "failure" | "rate_limited" | "no_outcome";
            /** Observedat */
            observedAt?: string | null;
            /** Errorcode */
            errorCode?: string | null;
        };
        /** NeighbourPageDto */
        NeighbourPageDto: {
            /** Functionid */
            functionId: number;
            /** Direction */
            direction: string;
            /** Group */
            group: string;
            /** Rows */
            rows: components["schemas"]["NeighbourRowDto"][];
            /** Total */
            total: number;
            /** Totalprimary */
            totalPrimary: number;
            /** Totalutility */
            totalUtility: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Callerssuppressed */
            callersSuppressed: boolean;
            /** Maybeincomplete */
            mayBeIncomplete: boolean;
        };
        /**
         * NeighbourRowDto
         * @description One row in a card's caller/callee table.
         *
         *     Deliberately narrow — no code, no long summary (TAD §3.4).
         */
        NeighbourRowDto: {
            /** Id */
            id: number;
            /** Address */
            address: number;
            /** Displayname */
            displayName: string;
            /** Namellm */
            nameLlm: string | null;
            /** Isrenamed */
            isRenamed: boolean;
            /** Summaryshort */
            summaryShort: string | null;
            /** Summarystatus */
            summaryStatus: string;
            /** Summarylowconfidence */
            summaryLowConfidence: boolean;
            /** Kind */
            kind: string;
            /** Oncanvas */
            onCanvas: boolean;
            /** Isutility */
            isUtility: boolean;
            /** Utilitysource */
            utilitySource: string;
            /** Fanin */
            fanIn: number;
            /** Isself */
            isSelf: boolean;
            /** Hasnotes */
            hasNotes: boolean;
            /** Canfanout */
            canFanOut: boolean;
        };
        /**
         * OpenFunctionResultDto
         * @description Ordered outcome for one supplied runtime address.
         */
        OpenFunctionResultDto: {
            /** Inputaddress */
            inputAddress: string;
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "duplicate" | "invalid" | "unresolved";
            /** Canonicaladdress */
            canonicalAddress?: number | null;
            /** Functionid */
            functionId?: number | null;
            /** Displayname */
            displayName?: string | null;
            /** Message */
            message?: string | null;
        };
        /**
         * OpenFunctionsRequestDto
         * @description Runtime addresses to resolve and add to one view.
         */
        OpenFunctionsRequestDto: {
            /** Addresses */
            addresses: string[];
            /** Dllbase */
            dllBase: string;
        };
        /**
         * OpenFunctionsResponseDto
         * @description Bulk-open report plus the complete reconciled view-node state.
         */
        OpenFunctionsResponseDto: {
            /** Results */
            results: components["schemas"]["OpenFunctionResultDto"][];
            /** Nodes */
            nodes: components["schemas"]["ViewNodeDto"][];
            /** Rootfunctionid */
            rootFunctionId: number | null;
        };
        /**
         * QueueSnapshotDto
         * @description ``GET /queue`` (endpoint 20) — the chip's data source.
         */
        QueueSnapshotDto: {
            /** Inflight */
            inFlight: components["schemas"]["InFlightItemDto"][];
            /** Queued */
            queued: components["schemas"]["QueuedItemDto"][];
            /** Inflightcount */
            inFlightCount: number;
            /** Queuedcount */
            queuedCount: number;
            /** Pauseduntil */
            pausedUntil?: string | null;
        };
        /** QueuedItemDto */
        QueuedItemDto: {
            /** Functionid */
            functionId: number;
            /** Displayname */
            displayName: string;
            /** Priority */
            priority: number;
        };
        /**
         * SetLastViewRequestDto
         * @description ``POST /binaries/{id}/last-view`` request body (B16, I6). A dedicated
         *     endpoint rather than a side effect of ``GET /views/{id}`` — GETs stay
         *     side-effect free everywhere in this API.
         */
        SetLastViewRequestDto: {
            /** Viewid */
            viewId: number;
        };
        /**
         * SummaryDemandRequestDto
         * @description ``POST /functions/{id}/summary`` request body.
         *
         *     ``reason`` is logging-only (card|table_row|detail|prefetch); it never
         *     affects queueing behaviour, only what shows up in structured logs.
         *
         *     ``priority`` is bounded to `SummaryQueue`'s own
         *     [`MIN_PRIORITY`, `MAX_PRIORITY`] range at the DTO layer, so an
         *     out-of-range value fails FastAPI's 422 validation *before* any DB write
         *     happens — previously an out-of-range priority reached
         *     `services.summary_service.demand_summary`, whose own `queue.enqueue`
         *     raised `ValueError` (an unhandled 500) after the row had already been
         *     flipped to `summary_status='pending'`, stranding it there until the
         *     next boot's `recover_pending_summaries` sweep.
         */
        SummaryDemandRequestDto: {
            /** Priority */
            priority: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SummaryDemandResponseDto
         * @description ``POST /functions/{id}/summary`` response — always one of:
         *
         *     - **202** with ``summary_status="pending"`` and a ``queue_position``
         *       (C5a: this endpoint never blocks on the LLM).
         *     - **200** with the cached result already in ``summary_status="ready"``
         *       (C3: cache-first, no work scheduled).
         */
        SummaryDemandResponseDto: {
            /** Functionid */
            functionId: number;
            /** Summarystatus */
            summaryStatus: string;
            /** Queueposition */
            queuePosition?: number | null;
            /** Summaryshort */
            summaryShort?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViewCreateDto
         * @description ``POST /binaries/{id}/views`` request body (B8/B9).
         */
        ViewCreateDto: {
            /** Name */
            name: string;
        };
        /**
         * ViewDto
         * @description The full view record (TAD §3.4) -- ``GET /views/{id}``'s response, and
         *     the response shape for create/patch/duplicate.
         */
        ViewDto: {
            /** Id */
            id: number;
            /** Binaryid */
            binaryId: number;
            /** Name */
            name: string;
            /** Rootfunctionid */
            rootFunctionId: number | null;
            camera: components["schemas"]["CameraDto"];
            /** Nodes */
            nodes: components["schemas"]["ViewNodeDto"][];
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * ViewNodeDto
         * @description One placed node (TAD §3.4). ``functionId`` is the stable identity key
         *     the client reconciles on -- there is no separate node id on the wire.
         */
        ViewNodeDto: {
            /** Functionid */
            functionId: number;
            /** Visible */
            visible: boolean;
            /** Collapsed */
            collapsed: boolean;
            /** Color */
            color: string | null;
            /** Posx */
            posX: number;
            /** Posy */
            posY: number;
            /** Pinned */
            pinned: boolean;
            /** Originfunctionid */
            originFunctionId: number | null;
            /**
             * Originkind
             * @enum {string}
             */
            originKind: "root" | "fanout" | "callstack" | "fanin";
            /** Originimplied */
            originImplied: boolean;
        };
        /**
         * ViewNodeUpsertDto
         * @description One entry in the ``upsert`` array of the batch node-patch request
         *     (TAD §4.3 #12). Every field but ``functionId`` is optional: a partial
         *     patch of an existing row leaves omitted fields untouched; a brand-new row
         *     gets the repository-level defaults for anything omitted.
         */
        ViewNodeUpsertDto: {
            /** Functionid */
            functionId: number;
            /** Visible */
            visible?: boolean | null;
            /** Collapsed */
            collapsed?: boolean | null;
            /** Color */
            color?: string | null;
            /** Posx */
            posX?: number | null;
            /** Posy */
            posY?: number | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Originfunctionid */
            originFunctionId?: number | null;
            /** Originkind */
            originKind?: ("root" | "fanout" | "callstack" | "fanin") | null;
            /** Originimplied */
            originImplied?: boolean | null;
        };
        /**
         * ViewNodesPatchRequestDto
         * @description ``PATCH /views/{id}/nodes`` request body (E3).
         */
        ViewNodesPatchRequestDto: {
            /** Upsert */
            upsert?: components["schemas"]["ViewNodeUpsertDto"][];
            /** Remove */
            remove?: number[];
        };
        /**
         * ViewNodesPatchResponseDto
         * @description The full post-state of every node in the view, so the client can
         *     reconcile (TAD §4.3 #12).
         */
        ViewNodesPatchResponseDto: {
            /** Nodes */
            nodes: components["schemas"]["ViewNodeDto"][];
        };
        /**
         * ViewPatchDto
         * @description ``PATCH /views/{id}`` request body (E3a) -- name/root/camera, all
         *     optional-and-absent-means-"leave unchanged" (``model_fields_set``, same
         *     idiom as ``FunctionUpdateDto``).
         */
        ViewPatchDto: {
            /** Name */
            name?: string | null;
            /** Rootfunctionid */
            rootFunctionId?: number | null;
            camera?: components["schemas"]["CameraDto"] | null;
        };
        /** ViewSummaryDto */
        ViewSummaryDto: {
            /** Id */
            id: number;
            /** Binaryid */
            binaryId: number;
            /** Name */
            name: string;
            /** Rootfunctionid */
            rootFunctionId: number | null;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfigDto"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    get_llm_status_api_v1_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatusDto"];
                };
            };
        };
    };
    probe_llm_status_api_v1_llm_status_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProbeDto"];
                };
            };
        };
    };
    list_binaries_api_v1_binaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinarySummaryDto"][];
                };
            };
        };
    };
    import_binary_api_v1_binaries_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobAcceptedDto"];
                };
            };
        };
    };
    decompile_binary_api_v1_binaries_decompile_post: {
        parameters: {
            query: {
                name: string;
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobAcceptedDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_status_api_v1_binaries_imports__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobStatusDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_import_api_v1_binaries_imports__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobStatusDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_binary_api_v1_binaries__binary_id__delete: {
        parameters: {
            query: {
                confirm: string;
            };
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_points_api_v1_binaries__binary_id__entry_points_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPointsDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_binary_functions_api_v1_binaries__binary_id__functions_get: {
        parameters: {
            query?: {
                /** @description Substring filter (B11/E1a). */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionSearchPageDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_function_by_address_api_v1_binaries__binary_id__functions_by_address_get: {
        parameters: {
            query: {
                /** @description Hex (`0x...`) or decimal address (D2). */
                address: string;
            };
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_function_api_v1_functions__function_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_function_api_v1_functions__function_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FunctionUpdateDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbours_api_v1_functions__function_id__neighbours_get: {
        parameters: {
            query: {
                /** @description Required — on_canvas is a view fact (E2). */
                viewId: number;
                direction?: "callees" | "callers";
                group?: "primary" | "utility";
                limit?: number;
                offset?: number;
                sort?: ("callOrder" | "name" | "address" | "fanIn") | null;
                order?: "asc" | "desc";
                /** @description Substring over name + summaryShort (D22). */
                filter?: string | null;
            };
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighbourPageDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_binary_views_api_v1_binaries__binary_id__views_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewSummaryDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_binary_view_api_v1_binaries__binary_id__views_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewCreateDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_last_view_api_v1_binaries__binary_id__last_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLastViewRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_api_v1_views__view_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_view_api_v1_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_view_api_v1_views__view_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewPatchDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_view_api_v1_views__view_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_view_nodes_api_v1_views__view_id__nodes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewNodesPatchRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewNodesPatchResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_functions_api_v1_views__view_id__open_functions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenFunctionsRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenFunctionsResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demand_summary_api_v1_functions__function_id__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryDemandRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDemandResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_summary_api_v1_functions__function_id__summary_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_binary_summaries_api_v1_binaries__binary_id__summaries_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binary_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_summary_api_v1_functions__function_id__summary_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                function_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDemandResponseDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshotDto"];
                };
            };
        };
    };
    cancel_pending_api_v1_queue_cancel_pending_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelPendingResponseDto"];
                };
            };
        };
    };
    get_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
