// Placeholder for `openapi-typescript` output. Generated by `just gen-types`
// once the API is running (`npm run gen-types` in frontend/). Do not edit by
// hand; `src/api/types.ts` holds the curated aliases that component code
// should import instead.
export type components = Record<string, never>;
