"""initial

Authoritative schema per TAD §3.3: binaries, functions, edges, views,
view_nodes, plus the app_meta bookkeeping table (F1b). This migration is the
*only* way a GraphRev database is created — there is no metadata.create_all
path, even in dev/tests (docs/adr/0002-alembic-in-v0.md), a deliberate
deviation from PRD §5.2's "migrations ... out of scope" for v0.

Revision ID: 0001
Revises:
Create Date: 2026-08-21 13:06:23.609066

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from graphrev.core.config import get_settings

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_meta",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_meta")),
    )
    op.create_table(
        "binaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("last_view_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_view_id"],
            ["views.id"],
            name="fk_binaries_last_view_id_views",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_binaries")),
        sa.UniqueConstraint("name", "version", name="ux_binaries_name_version"),
    )
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("binary_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.Integer(), nullable=False),
        sa.Column("name_ghidra", sa.String(), nullable=False),
        sa.Column("parameters", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=True),
        sa.Column("assembly", sa.String(), nullable=True),
        sa.Column("code_c", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("placeholder_module", sa.String(), nullable=True),
        sa.Column("fan_in", sa.Integer(), nullable=False),
        sa.Column("fan_out", sa.Integer(), nullable=False),
        sa.Column("is_utility", sa.Boolean(), nullable=False),
        sa.Column("summary_short", sa.String(), nullable=True),
        sa.Column("summary_long", sa.String(), nullable=True),
        sa.Column("summary_status", sa.String(), nullable=False),
        sa.Column("summary_model", sa.String(), nullable=True),
        sa.Column("summary_error_code", sa.String(), nullable=True),
        sa.Column("summary_low_confidence", sa.Boolean(), nullable=False),
        sa.Column("summary_generated_at", sa.String(), nullable=True),
        sa.Column("summary_input_hash", sa.String(), nullable=True),
        sa.Column("name_analyst", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("notes_updated_at", sa.String(), nullable=True),
        sa.Column("utility_override", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column(
            "is_utility_effective",
            sa.Boolean(),
            sa.Computed(
                "CASE utility_override WHEN 'always' THEN 1 WHEN 'never' THEN 0 ELSE is_utility END",
                persisted=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('normal', 'import', 'thunk', 'external', 'placeholder')",
            name=op.f("ck_functions_kind_valid"),
        ),
        sa.CheckConstraint(
            "summary_status IN ('none', 'pending', 'ready', 'error', 'stale')",
            name=op.f("ck_functions_summary_status_valid"),
        ),
        sa.CheckConstraint(
            "utility_override IS NULL OR utility_override IN ('always', 'never')",
            name=op.f("ck_functions_utility_override_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["binary_id"],
            ["binaries.id"],
            name=op.f("fk_functions_binary_id_binaries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_functions")),
        sa.UniqueConstraint("binary_id", "address", name="ux_functions_binary_address"),
    )
    with op.batch_alter_table("functions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_functions_binary_analystname", ["binary_id", "name_analyst"], unique=False
        )
        batch_op.create_index(
            "ix_functions_binary_name", ["binary_id", "name_ghidra"], unique=False
        )
        batch_op.create_index("ix_functions_fanin", ["binary_id", "fan_in"], unique=False)
        batch_op.create_index("ix_functions_status", ["summary_status"], unique=False)
        batch_op.create_index(
            "ix_functions_utility_eff", ["binary_id", "is_utility_effective"], unique=False
        )

    op.create_table(
        "edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("binary_id", sa.Integer(), nullable=False),
        sa.Column("caller_id", sa.Integer(), nullable=False),
        sa.Column("callee_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.CheckConstraint("kind IN ('call')", name=op.f("ck_edges_kind_valid")),
        sa.ForeignKeyConstraint(
            ["binary_id"],
            ["binaries.id"],
            name=op.f("fk_edges_binary_id_binaries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["callee_id"],
            ["functions.id"],
            name=op.f("fk_edges_callee_id_functions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["caller_id"],
            ["functions.id"],
            name=op.f("fk_edges_caller_id_functions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint("caller_id", "callee_id", name="ux_edges_pair"),
    )
    with op.batch_alter_table("edges", schema=None) as batch_op:
        batch_op.create_index("ix_edges_callee", ["callee_id"], unique=False)
        batch_op.create_index("ix_edges_caller", ["caller_id"], unique=False)

    op.create_table(
        "views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("binary_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("root_function_id", sa.Integer(), nullable=True),
        sa.Column("camera_x", sa.Float(), nullable=False),
        sa.Column("camera_y", sa.Float(), nullable=False),
        sa.Column("camera_zoom", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["binary_id"],
            ["binaries.id"],
            name=op.f("fk_views_binary_id_binaries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_function_id"],
            ["functions.id"],
            name=op.f("fk_views_root_function_id_functions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_views")),
    )
    with op.batch_alter_table("views", schema=None) as batch_op:
        batch_op.create_index("ix_views_binary", ["binary_id"], unique=False)

    op.create_table(
        "view_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("view_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("collapsed", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("pos_x", sa.Float(), nullable=False),
        sa.Column("pos_y", sa.Float(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("origin_function_id", sa.Integer(), nullable=True),
        sa.Column("origin_kind", sa.String(), nullable=False),
        sa.Column("origin_implied", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "origin_kind IN ('root', 'fanout', 'callstack')",
            name=op.f("ck_view_nodes_origin_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.id"],
            name=op.f("fk_view_nodes_function_id_functions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["origin_function_id"],
            ["functions.id"],
            name=op.f("fk_view_nodes_origin_function_id_functions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["view_id"], ["views.id"], name=op.f("fk_view_nodes_view_id_views"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_view_nodes")),
        sa.UniqueConstraint("view_id", "function_id", name="ux_view_nodes_view_id_function_id"),
    )
    with op.batch_alter_table("view_nodes", schema=None) as batch_op:
        batch_op.create_index("ix_view_nodes_origin", ["origin_function_id"], unique=False)
        batch_op.create_index("ix_view_nodes_view", ["view_id", "visible"], unique=False)

    # ### end Alembic commands ###

    # Seed app_meta: schema_version for humans inspecting the DB, and
    # utility_fanin_threshold so the F1b startup hook has a baseline to diff
    # against on the very first boot (otherwise it can't detect "changed").
    settings = get_settings()
    app_meta = sa.table(
        "app_meta",
        sa.column("key", sa.String()),
        sa.column("value", sa.String()),
    )
    op.bulk_insert(
        app_meta,
        [
            {"key": "schema_version", "value": "0001"},
            {
                "key": "utility_fanin_threshold",
                "value": str(settings.utility_fanin_threshold),
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("view_nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_view_nodes_view")
        batch_op.drop_index("ix_view_nodes_origin")

    op.drop_table("view_nodes")
    with op.batch_alter_table("views", schema=None) as batch_op:
        batch_op.drop_index("ix_views_binary")

    op.drop_table("views")
    with op.batch_alter_table("edges", schema=None) as batch_op:
        batch_op.drop_index("ix_edges_caller")
        batch_op.drop_index("ix_edges_callee")

    op.drop_table("edges")
    with op.batch_alter_table("functions", schema=None) as batch_op:
        batch_op.drop_index("ix_functions_utility_eff")
        batch_op.drop_index("ix_functions_status")
        batch_op.drop_index("ix_functions_fanin")
        batch_op.drop_index("ix_functions_binary_name")
        batch_op.drop_index("ix_functions_binary_analystname")

    op.drop_table("functions")
    op.drop_table("binaries")
    op.drop_table("app_meta")
    # ### end Alembic commands ###
